//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABSENC> ABSENCs { get; set; }
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<BUILDING> BUILDINGs { get; set; }
        public virtual DbSet<CAR> CARs { get; set; }
        public virtual DbSet<CARPARK> CARPARKs { get; set; }
        public virtual DbSet<COMPLAIN> COMPLAINs { get; set; }
        public virtual DbSet<EXPEND> EXPENDs { get; set; }
        public virtual DbSet<FITNESS> FITNESSes { get; set; }
        public virtual DbSet<LATE> LATEs { get; set; }
        public virtual DbSet<LAUNDRY> LAUNDRies { get; set; }
        public virtual DbSet<LEAVE> LEAVEs { get; set; }
        public virtual DbSet<METER> METERs { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<REGULAROOM> REGULAROOMs { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<SALARYTB> SALARYTBs { get; set; }
        public virtual DbSet<VIPROOM> VIPROOMs { get; set; }
        public virtual DbSet<WORKTIME> WORKTIMEs { get; set; }
    }
}
