//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int IDBILL { get; set; }
        public Nullable<decimal> FITNESSBILL { get; set; }
        public decimal ELECTRICITYBILL { get; set; }
        public decimal WATERBILL { get; set; }
        public Nullable<decimal> INTERNETBILL { get; set; }
        public Nullable<int> CLEANBILL { get; set; }
        public System.DateTime DATEBILL { get; set; }
        public string STATUS { get; set; }
        public int IDBUILDING { get; set; }
        public long IDRECEIVER { get; set; }
        public int IDROOM { get; set; }
    
        public virtual BUILDING BUILDING { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
