//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARPARK
    {
        public int NO { get; set; }
        public string TIMEIN { get; set; }
        public string TIMEOUT { get; set; }
        public int CARNUMBER { get; set; }
        public string PROVINCE { get; set; }
        public long IDRECORDER { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
