//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPEND
    {
        public int ID { get; set; }
        public string DETAIL { get; set; }
        public int PRICE { get; set; }
        public System.DateTime DATEEXPEND { get; set; }
        public long IDRECORDER { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
