//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FITNESS
    {
        public int NO { get; set; }
        public Nullable<long> RESIDENT { get; set; }
        public Nullable<System.DateTime> DAY { get; set; }
        public string TIME { get; set; }
        public Nullable<int> PRICE { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
