//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAUNDRY
    {
        public int ID { get; set; }
        public int ROOM { get; set; }
        public int BUILDING { get; set; }
        public System.DateTime DATELAUNDRY { get; set; }
        public int PRICE { get; set; }
        public string STATUS { get; set; }
    
        public virtual ROOM ROOM1 { get; set; }
    }
}
