//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON()
        {
            this.ABSENCs = new HashSet<ABSENC>();
            this.BILLs = new HashSet<BILL>();
            this.BUILDINGs = new HashSet<BUILDING>();
            this.CARs = new HashSet<CAR>();
            this.CARPARKs = new HashSet<CARPARK>();
            this.COMPLAINs = new HashSet<COMPLAIN>();
            this.EXPENDs = new HashSet<EXPEND>();
            this.FITNESSes = new HashSet<FITNESS>();
            this.LATEs = new HashSet<LATE>();
            this.LEAVEs = new HashSet<LEAVE>();
            this.WORKTIMEs = new HashSet<WORKTIME>();
        }
        [Required(ErrorMessage = "Please Enter IDCARD")]       
        public long IDCARD { get; set; }
        [Required(ErrorMessage = "Please Enter Username")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "Please Enter Password")]
        public string PASSWORD { get; set; }
        [Required(ErrorMessage = "Please Enter NAME")]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Please Enter LastName")]
        public string LASTNAME { get; set; }
        public string GENDER { get; set; }
        public string POSITION { get; set; }
        public Nullable<int> IDROOM { get; set; }
        [Required(ErrorMessage = "Please Enter HIREDATE DD/MM/YYYY")]
        public System.DateTime HIREDATE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONENUMBER { get; set; }
        public Nullable<int> IDBUILDING { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABSENC> ABSENCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUILDING> BUILDINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR> CARs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARPARK> CARPARKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPLAIN> COMPLAINs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPEND> EXPENDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FITNESS> FITNESSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LATE> LATEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAVE> LEAVEs { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual SALARYTB SALARYTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKTIME> WORKTIMEs { get; set; }
    }
}
