//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGULAROOM
    {
        public string SEVICE { get; set; }
        public string INTERNET { get; set; }
        public int IDROOM { get; set; }
        public int IDBUILDING { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual ROOM ROOM { get; set; }
    }
}
