//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.LAUNDRies = new HashSet<LAUNDRY>();
            this.METERs = new HashSet<METER>();
            this.People = new HashSet<PERSON>();
        }
    
        public int IDROOM { get; set; }
        public string STATUS { get; set; }
        public string MAID { get; set; }
        public string CLEANTIME { get; set; }
        public string CLEANDATE { get; set; }
        public int IDBUILDING { get; set; }
    
        public virtual BUILDING BUILDING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAUNDRY> LAUNDRies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METER> METERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON> People { get; set; }
        public virtual REGULAROOM REGULAROOM { get; set; }
        public virtual VIPROOM VIPROOM { get; set; }
    }
}
